### PR TITLE
Added Links to footer!

### PR DESCRIPTION
**Pull request by avinIndrasoma**
@Safnaj @Shehanka #54  I have added the links to the footer of the site,
The links I have added are Github, Discord, Twitter, Instagram, YouTube, and Facebook
(I have taken a non-expiring link for the discord server so if there is any issue you can manually revoke it within server settings!)

however, I could not preview it due to an issue on my side so do lemme know if there is anything that needs to be changed!

Ps: @nimeshkavinda thanks for letting me take the issue! :) :octocat:

### CODE REVIEW

**Comment by avinIndrasoma** [comment]
@Safnaj 
image
Is this okay?

**Comment by Safnaj** [comment]
> @Safnaj image Is this okay?

its not aligned. and please resolve the conflicts

**Comment by avinIndrasoma** [comment]
@Safnaj done 
image

**Comment by avinIndrasoma** [comment]
@Safnaj It got into a different PR somehow please merge that and close this!

**Pull request closed without merging**
